### ISSUE TITLE
Minor schematic errors in documentation

### ISSUE THREAD

**Issue by darkside90a** [mp-se/gravitymon#121]
**Describe the bug**
Great project!
I found some issues in the schematics in the hardware section of the documentation:
1. Battery orientation is wrong. Could be misleading if anyone follows the schematic literally
2. Reset pins available on the iSpindel PCB are missing (RST <--> GND)
3. Now I feel a bit picky: Replace name of U1 ("WEMOS-D1-MINI") to "ESP32-x"

**Software:**
 - Platform (esp8266, esp32)
 - Version 1.2.0

Cheers
Lars

**Comment by mp-se** [comment]
Thanks for spotting those issues, I will take care of them.

**Comment by mp-se** [comment]
Fixed the battery schematics. The reset connections are specific to the PCB design, added links to the most common PCB options for more information. 

Changes the text on the U1 chip on the ESP32 design (could not find a suitable component in the component library).
