### ISSUE TITLE
Temp sensor not detected on c3 v2+ build

### ISSUE THREAD

**Issue by mp-se** [mp-se/gravitymon#145]
Temp sensor is not detected on the C3 v2.1 chip, works on v1.0

**Comment by hutten0** [comment]
I have 2 iSpindels with 8266 chip, flashed with both of them with v1.3.0-beta2 build.
On one of them didn’t detect the temp sensor.
Unfortunately this one is in the fermenter at the moment so I can’t test the latest build..

**Comment by mp-se** [comment]
Thanks, I will have a look. Would be good to get the log output from the one that is not working when you can.

**Comment by mp-se** [comment]
Probably related to #143, revert to older arduino version for stability.

**Comment by mp-se** [comment]
GPIO pins where wrong so temp sensor and battery (pins where swapped) has never worked on this chip...
