### ISSUE TITLE
gravitymon 1.3.0 connection to BrewPiLess - angle display question

### ISSUE THREAD

**Issue by Hwerow** [mp-se/gravitymon#156]
Hi
I have connected gravitymon 1.3.0  to BrewPiLess for the first time and noticed that the angle display has far too many decimal places. 
![image](https://github.com/mp-se/gravitymon/assets/38124525/fcfd59de-a134-432d-8fb9-1db5b03f6318)

I am not sure whether this is a gravitymon sending problem or a BrewPiLess formatting problem

Please could you advise

Thanks

**Comment by mp-se** [comment]
It should not be gravitymon, i have testcases that verify number of decimals. I noticed that newer versions of arduino json can cause this problem.

**Comment by Hwerow** [comment]
Thanks I will get onto Vito Cheers
