### ISSUE TITLE
InfluxDB error code -1

### ISSUE THREAD

**Issue by jackjohnsonuk** [mp-se/gravitymon#158]
Hi Magnus,

Not sure if it's a bug as such, or me just missing something.

I can't get GravityMon to talk to Influx.  I've setup an Organisation, a bucket, and generated an api key, but keep getting:

Push target 'influxdb' failed with error code -1

Any idea where to start?

Many thanks

Jack

**Comment by mp-se** [comment]
You can find the error codes under troubleshooing in the docs.

-1 means connection refused so either a firewall is blocking or the influx listener is not up and running

**Comment by jackjohnsonuk** [comment]
Thanks so much for the quick response - it was my firewall, turns out I'd forgotten to allow my vlan to talk to influx!

I am now getting:

Push target 'influxdb' failed with error code 400, bad request

Sorry, I'm new to influxdb v2.. so I might be missing something really obvious

**Comment by mp-se** [comment]
Error 400 means that there is a data error in the payload, some value that is incorrect. Can you use the test function to see what the sent data is?

**Comment by mp-se** [comment]
I'm closing this since there is no more information on the topic. Please reopen if problem persists.

**Comment by jackjohnsonuk** [comment]
Sorry Magnus, I meant to come back and close this, but fell off the radar.  You're guidance in it being a payload issue helped massively.

For anyone else who may come across this issue, my problem was related to the firewall, and specifically traffic crossing VLAN's.

Many thanks for your assistance with sorting this.  I'm now a very happy used of GravityMon.  It's a great project, and working brilliantly for me.

**Comment by mp-se** [comment]
No problems, I thought you solved it since it was a networking problem. 

Thanks for the kind words, its always good to know that you find the software valuable. If you have any improvement suggestsion please let me know. I have run out of ideas for the momement.
