### ISSUE TITLE
Add skip interval for gyro measurements

### ISSUE THREAD

**Issue by DMT07** [mp-se/gravitymon#180]
**Is your feature request related to a problem? Please describe.**
The gyro uses a lot more energy than the DS18B20 temperature sensor. For applications where you want to use the iSpindel as the beer temperature sensor, you ideally want more regular temperature updates than tilt angle updates. If there was an option to set a skip interval for the gyro measurements, more frequent temperature readings can be sent for the same battery life.

**Describe the solution you'd like**
In the configuration, under the "Advanced Software Settings" tab, add an option "Skip interval - gyro update". When the skip interval > 0, the gyro reading is treated as sample and hold (last actual reading is reported during the skipped cycles).

**Comment by mp-se** [comment]
If you use the temperature sensor on 12 bits it will consume as much power as the gyro, its not the sensors that consume power its the esp itself. But I like your Idea of having the possibility to send updates for one or the other sensor more frequent.   

Would a setting to disable the qyro always make sense if a user wants to use the device as a temperature probe`?

The challenge is probably what data format to use when there is no angle or gravity data. Should there be different format templates with and without angle/gravity? Should the value be set to a zero? How would the server side interpret the data ?

**Comment by mp-se** [comment]
I actually created a fork that only works as a temp sensor. This was a request by a user. So it would be good to get that fork archived. 

The problem with missing data is that the server might throw an exception of the field is missing.    The format template would not know  what data to omit either. So sending a dummy value (or perhaps the last known gravit) is probably the easiest option

**Comment by mp-se** [comment]
Closing this since there is no good solution for the request
