### ISSUE TITLE
New iSpindel build. Config Unable to Calibrate gyro C3  2.0.0 Beta 2

### ISSUE THREAD

**Issue by Hwerow** [mp-se/gravitymon#187]
**Describe the bug**
Unable  to configure the gyro click the button says configured Home page says not
also Temperature sensor not recognised but works ok in 1.4.1

**To Reproduce**
1. Go to '...' Configuration
2. Click on '....' initialise gyro save page
3. .says configured but on the home page says not

**Expected behavior**

**Screenshots**

**Software:**
 - Platform (esp8266, esp32) esp32-C3
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 1229.0.1 64 bit

**Additional context**

**Comment by mp-se** [comment]
I'm aware of this issue on the c3 board. From what I have been able to figure out it's an issue with arduino / esp-idf framework so I havent been able to find a way around this yet. Upgrading to arduino 3.0 is something i'm looking into to see if that can fix the problem. So for now the 1.4 version is the latest one that works with the c3 board. I have focused on getting the software working and have not dug into the details with each board.

**Comment by Hwerow** [comment]
Thanks

**Comment by mp-se** [comment]
Same as #184

**Comment by mp-se** [comment]
Finally found the issue so this will be fixed included in the next release. The drawback is that it was the LED that was in conflict so I have to disable that functionality on the ESP32c3

**Comment by mp-se** [comment]
Once the build is completed you can try the version in the dev branch under bin, that should now work on the c3

**Comment by Hwerow** [comment]
Thanks Magnus. Small correction Home menu IP Adress should be Address. Cheers Peter
