### ISSUE TITLE
No temperature sensor detected when upgrading to 2.0.0-beta3

### ISSUE THREAD

**Issue by mburgess00** [mp-se/gravitymon#193]
**Describe the bug**
The UI reports no temperature sensor detected after upgrading from 2.0.0-beta2 to 2.0.0-beta3

**To Reproduce**
1. flash 2.0.0-beta3
2. observe the error

**Expected behavior**
temperature sensor should work

**Screenshots**
![image](https://github.com/user-attachments/assets/13766aed-dcb0-4f70-b23b-a6f739e3af7e)

**Software:**
 - Platform esp8266
 - Browser firefox
 - Version 2.0.0-beta3

**Additional context**
Opensourcedistilling Jeffrey 2.69

**Comment by mp-se** [comment]
Can you try the build in the dev branch? Ive changed the temp library which seams to fix this on some of my builds. I have seen this on ocassion myswlf

**Comment by mburgess00** [comment]
It does seem to work on the dev branch build

**Comment by mp-se** [comment]
Perfect, that confirms my suspicion.  It fixed the issue on some of my build. I will make this the standard version for the next build. Wonder if that could have something to do with clone sensors ?

**Comment by mp-se** [comment]
Does it work with the ispindle software?

**Comment by phariseo** [comment]
@mp-se - I do have an original Dallas DS18B20 (100% original - from the authorized distributor), and it behaves the same on Beta3.
worked flawlessly on older 1.x branch of GravityMon, works flawlessly on Dev as well.

**Comment by mp-se** [comment]
> @mp-se - I do have an original Dallas DS18B20 (100% original - from the authorized distributor), and it behaves the same on Beta3. worked flawlessly on older 1.x branch of GravityMon, works flawlessly on Dev as well. Board is an Jeffrey 2.69

This is really strange, my code is the same and has not changed in quite a while. Must be some combination of libraries that I use that does not work in the same way... not really easy to pinpoint. 

The OneWire library has been used since the beginning but its not really maintained any more, but the new OneWireNG seams to work better. I actually changed some temp sensors on my builds before I figured out it was a software problem

**Comment by mburgess00** [comment]
Okay did some testing on one unit. iSpindel 7.3.3 firmware does work

iSpindel-7.3.3:
![image](https://github.com/user-attachments/assets/5a0949e8-35d2-4b97-bf00-bb4e5eaab0b0)


Gravitymon 2.0.0-beta2
![image](https://github.com/user-attachments/assets/2e7cf17b-1907-4e25-9682-a7e3931558c9)

Gravitymon 2.0.0 dev branch
![image](https://github.com/user-attachments/assets/689a3161-a68f-4737-9525-3add3d541b33)

**Comment by mp-se** [comment]
Great news, then that is confirmed. I will use the new library in the future.
