### ISSUE TITLE
Old iSpindel configuration cannot be deleted.

### ISSUE THREAD

**Issue by makuip** [mp-se/gravitymon#202]
Gravmon reports that an iSpindel configuration was found and offers to import or delete it. When I click on "delete" an error message "Page not found! /other/links is not a valid URL for this application!" appears.

1. Take a device with an old iSpindel configuration.
2. Click on 'delete' in the notification that the iSpindel configuration can be imported or deleted.

I would expect to see a page where I can delete the old iSpindel configuration.

Software:
 - Platform: esp8266, Version, 2.0.1
 - Browser: Edge, Version 131.0.2903.86

![gravmon_error](https://github.com/user-attachments/assets/4c9c014c-33e0-4d07-9fc7-180163015283)

**Comment by mp-se** [comment]
thanks, I will fix that.

**Comment by mp-se** [comment]
Fixed in beta 2
