### ISSUE TITLE
Temp Sensor Adj Problem

### ISSUE THREAD

**Issue by StodgyWaif** [mp-se/gravitymon#46]
Hello.
I changed my OTA Base URL to:
https://github.com/mp-se/gravitymon/tree/master/bin/
(Not sure if this is correct or not)

And the Temp Sensor Adj value automatically goes to -17.77778.
I tried changing it to 0 but it just goes back to that value.
Even after removing the OTA value I cannot set the Temp Sensor value back to 0.

I tried in both Chrome and Firefox.
This is on the 0.8.0 version.

EDIT:
By entering in +32 for the Temp Sensor Adj value it has reset back to 0.
After restarting the device it seems to be showing the correct temperature.

**Comment by mp-se** [comment]
Good find. This is another bug. Internally I use C as the standard format and I missed to convert this parameter if F was used. 

It should work to use the github URL for the OTA base, but I have not yet tested it. Its a good suggestion.

**Comment by mp-se** [comment]
Fixed in dev
