### ISSUE TITLE
Support for MPU6500  - Refer Discussion #73

### ISSUE THREAD

**Issue by Bananamannn** [mp-se/gravitymon#74]
Refer Discussion #73

**Comment by mp-se** [comment]
Patched library to accept both deviceID. Need help to validate feature. Will be part of beta2

**Comment by Bananamannn** [comment]
Happy to test when beta2 is available for download

**Comment by Bananamannn** [comment]
It appears to work just fine. No apparent error logs and tilt angle is registered

![image](https://user-images.githubusercontent.com/70923176/167066515-228c26da-15f3-4d2c-af31-a1efec4e255e.png)

**Comment by mp-se** [comment]
Good, then I will close this one. Expect the release to be out in a few weeks. Need to do some long term testing and probably a few bug fixes.
